name: Simple Test

on:
  push

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "branch=${BRANCH_NAME}"
        id: extract_branch
